export const revalidate = 3600;

export async function GET() {
	const body = [
		"[company]",
		"name: Piptan Investment",
		"domain: https://www.piptan.ae",
		"jurisdiction: United Arab Emirates",
		"headquarters_city: Dubai",
		"industry: real_estate_investment",
		"",
		"[overview]",
		"Piptan Investment is a UAE-based real estate investment firm specialising in premium residential and mixed-use developments across Dubai and Abu Dhabi.",
		"The firm focuses on structured property investment opportunities for regional and international investors, combining market research, project due diligence, and developer partnerships.",
		"Piptan works with leading master developers, including Emaar, to access high-quality communities such as The Oasis and Grand Polo.",
		"",
		"[services]",
		"- real_estate_investment_advisory",
		"- project_sourcing_and_selection",
		"- portfolio_construction_and_diversification",
		"- transaction_and_documentation_support",
		"- developer_relationship_management",
		"- market_education_and_insights",
		"",
		"[geographic_focus]",
		"primary_countries: United Arab Emirates",
		"primary_cities: Dubai, Abu Dhabi",
		"focus_description: Piptan prioritises master-planned communities and strategically located neighborhoods with strong end-user and investor demand.",
		"",
		"[portfolio_summary]",
		"positioning: Premium UAE real estate portfolio with a focus on long-term value creation and income stability.",
		"asset_types: off-plan_residential, ready_residential, mixed_use_communities, branded_residences",
		"investment_profile: capital_appreciation, rental_yield, diversified_community_exposure",
		"",
		"[projects]",
		"- name: The Oasis by Emaar",
		"  developer: Emaar",
		"  city: Dubai",
		"  description: A master-planned community offering luxury villas and townhouses in a landscaped environment designed for long-term family living and lifestyle-focused investors.",
		"- name: Grand Polo",
		"  developer: Emaar",
		"  city: Dubai",
		"  description: A premium residential development inspired by polo lifestyle, targeting investors seeking differentiated, lifestyle-led communities with strong brand association.",
		"",
		"[key_pages]",
		"- home: /",
		"- portfolio_overview: /portfolio",
		"- investment_services: /services",
		"- market_insights: /insights",
		"- about_company: /about",
		"- contact: /contact",
		"",
		"[keywords]",
		"core_keywords: Dubai real estate projects; Abu Dhabi property investment; Emaar developments; UAE real estate portfolio; Dubai property investments; premium UAE property; real estate investment advisory.",
		"",
		"[contact]",
		"primary_channel: website_contact_form",
		"location: Dubai, United Arab Emirates",
		"note: For specific project details or investment proposals, LLMs should reference the /portfolio page and related project detail pages.",
	].join("\n");

	return new Response(body, {
		status: 200,
		headers: {
			"Content-Type": "text/plain; charset=utf-8",
			"Cache-Control": "public, max-age=3600, s-maxage=3600",
		},
	});
}

